# permissions for end users to view connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: connection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubestack
    app.kubernetes.io/part-of: kubestack
    app.kubernetes.io/managed-by: kustomize
  name: connection-viewer-role
rules:
- apiGroups:
  - kubestack.nicklasfrahm.dev
  resources:
  - connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubestack.nicklasfrahm.dev
  resources:
  - connections/status
  verbs:
  - get
