apiVersion: kubestack.nicklasfrahm.dev/v1alpha1
kind: Connection
metadata:
  labels:
    app.kubernetes.io/name: connection
    app.kubernetes.io/instance: delta
    app.kubernetes.io/part-of: kubestack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubestack
  name: alfa
spec:
  protocol: SSH
  secretRef:
    name: connection-alfa
    namespace: default
  